- name: install apache and php packages (AlmaLinux)
  tags: almalinux, apache, httpd
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "AlmaLinux"

- name: install apache and php packages (Ubuntu)
  tags: apache, apache2, ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
  when: ansible_distribution == "Ubuntu"

- name: start httpd (AlmaLinux)
  tags: almalinux, apache, httpd
  service:
    name: httpd
    state: started
    enabled: yes
  when: ansible_distribution == "AlmaLinux"

- name: copy default html file for site
  tags: apache, apache2, httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
