# This is part of bootstrap.yml
# - name: add ssh key for ansible user
#   authorized_key:
#     user: ansible
#     key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIExI57QW71y3WWwTe0kKlMFdvTFY2CphyRC1YxC6xZSL ansible"
# 

- name: install updates (AlmaLinux)
  tags: always
  dnf:
    update_cache: yes
  when: ansible_distribution == "AlmaLinux"

- name: install updates (Ubuntu)
  tags: always
  apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
